steps:
  # Install node_modules
  - name: node:16-alpine
    dir: backend
    entrypoint: npm
    args: 
      - install
    id: Install
  # Generate prisma schema
  - name: node:16-alpine
    entrypoint: npx
    args: 
      - prisma
      - generate
    id: Prisma
  # Create file .env from evironment variable
  - name: node:16-alpine
    dir: backend
    entrypoint: npm
    args: 
      - run
      - create-env
    env:
      - 'DATABASE_URL=$_DATABASE_DRIVER://$_DATABASE_USER:$_DATABASE_PASSWORD@$_DATABASE_HOST:$_DATABASE_PORT/$_DATABASE_NAME'
    id: Env
  # Build Image from Dockerfile
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - .infra/Dockerfile
    id: Build
  # Push Image to Cloud Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
  # Run Migration
  - name: node:16-alpine
    dir: backend
    entrypoint: npx
    args:
      - prisma
      - migrate
      - deploy
    id: Migration
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: nestjs-backend
  _DEPLOY_REGION: asia-northeast1
  _GCR_HOSTNAME: us.gcr.io
  _TRIGGER_ID: 8b355163-5deb-43e8-b846-45e5698ec06a
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - nestjs-backend
